apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: k8s.kubevault.com.pki.demo.pki-root/sign/k8s.kubevault.com.demo.pki-role
    server: http://vault.demo.svc:8200
    auth:
      kubernetes:
        role: "vault-issuer"
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer
