apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: vault-issuer
  namespace: demo
spec:
  vaultRef:
    name: vault
  vaultPolicyName: vault-issuer
  policyDocument: |
    path "k8s.kubevault.com.pki.demo.pki-root*"                                        { capabilities = ["read", "list"] }
    path "k8s.kubevault.com.pki.demo.pki-root/sign/k8s.kubevault.com.demo.pki-role"    { capabilities = ["create", "update"] }
    path "k8s.kubevault.com.pki.demo.pki-root/issue/k8s.kubevault.com.demo.pki-role"   { capabilities = ["create"] }